### ISSUE TITLE
how to works with ipv6 socks proxy?

### ISSUE THREAD

**Issue by sunshe35** [licyb200/sockslib#1]
I have an IPv6 address with a SOCKS5 service. 
I want to access the local network located at that address through this SOCKS5 service.
I do it using this code, but it doesn't work.
what should i do?

```python
import sockslib
import socket
auth_methods = [
        # Username / Password authentication
        sockslib.UserPassAuth(
            "socks5-user", "socks5-password"),
    ]

sockslib.set_default_proxy(('ipv6.website', 5008), auth=auth_methods)  # Set the default proxy
# Make the default socket object a SocksSocket
socket.socket = sockslib.SocksSocket
socket.socket.AF_INET6 = 10  # 设置IPv6地址族


# do something with network.

```

**Comment by woo200** [comment]
Is the proxy server an IPv6 address, or are you trying to connect to an ipv6 address through a proxy on ipv4?

Currently there is no way to specify a proxy that runs on ipv6, however I will add that functionality later today or tomorrow.

**Comment by woo200** [comment]
I have just updated the library, See https://github.com/woo200/sockslib#ipv6
Upgrade to sockslib v1.7.4

**Comment by sunshe35** [comment]
I'm trying to connect to an private ipv4 address through a socks5 proxy on ipv6, because I have only a ipv6 public address.
I have used the pysocks module, but it doesn't work on ipv6 socks service.  
The site https://github.com/woo200/sockslib#ipv6 doesn't work for me too. And I have upgrade to sockslib v1.7.4.

This is my code:
```python
import sockslib
import socket  # import socket for the protocol specifiers

with sockslib.SocksSocket(ip_protocol=socket.AF_INET6) as sock:
    auth_methods = [
        sockslib.UserPassAuth(
            "socks5-user", "socks5-password"),
    ]
    sock.set_proxy(('[2409:8a55:xxxx]', 5008), auth=auth_methods)


    import redis
    host = '192.168.10.136'
    port = 6379
    password = 'password'
    db = 0
    client = redis.Redis(host=host, port=port, db=db, password=password)
    result = client.zrevrange('key', 0, 10, withscores=True)
```

What should I do to solve my problem?

**Comment by woo200** [comment]
Could you please tell me what kind of error you are getting?
e.g. Socks authentication error, Connection refused, etc.

**Comment by sunshe35** [comment]
**You can translate chinese language through google.**

Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\redis\connection.py", line 707, in connect
    sock = self.retry.call_with_retry(
  File "E:\Anaconda3\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "E:\Anaconda3\lib\site-packages\redis\connection.py", line 708, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "E:\Anaconda3\lib\site-packages\redis\connection.py", line 1006, in _connect
    raise err
  File "E:\Anaconda3\lib\site-packages\redis\connection.py", line 994, in _connect
    sock.connect(socket_address)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败
。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\syncFolder\Project\test_me\test_socks3.py", line 22, in <module>
    result = client.zrevrange('key', 0, 10, withscores=True)
  File "E:\Anaconda3\lib\site-packages\redis\commands\core.py", line 4504, in zrevrange
    return self.execute_command(*pieces, **options)
  File "E:\Anaconda3\lib\site-packages\redis\client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "E:\Anaconda3\lib\site-packages\redis\connection.py", line 1461, in get_connection
    connection.connect()
  File "E:\Anaconda3\lib\site-packages\redis\connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10060 connecting to 192.168.10.136:6379. 由于连接方在一段时
间后没有正确答复或连接的主机没有反应，连接尝试失败。.

**Comment by woo200** [comment]
I believe I know what the issue you are having is. Since you're using redis, you must override the default socket with a proxy socket. Since default proxies are not supported for IPv6, I will update the library in a little bit to support this feature.

**Comment by sunshe35** [comment]
Thank you for your assistance. I appreciate your help.

**Comment by woo200** [comment]
Please upgrade to 1.7.5

Here is the updated code for you, of course, replace all the required placeholder information.

```python
import sockslib
import socket  # import socket for the protocol specifiers

auth_methods = [
  sockslib.UserPassAuth("socks5-user", 
                        "socks5-password"),
]
sockslib.set_default_proxy(('2409:8a55:xxxx', 5008), 
                          sockslib.Socks.SOCKS5, 
                          socket.AF_INET6, 
                          auth_methods)

socket.socket = sockslib.SocksSocket

import redis
host = '192.168.10.136'
port = 6379
password = 'password'
db = 0
client = redis.Redis(host=host, port=port, db=db, password=password)
result = client.zrevrange('key', 0, 10, withscores=True)
```

**Comment by sunshe35** [comment]
OK, It really works good for me. 
Thanks very much.

I asked ChatGPT and it only gave me the answer for pysocks, however pysocks does not support the ipv6 socks5 proxy. ChatGPT also told me there was no solution. 
Sockslib is the first network  to support ipv6 socks5 proxy module, I want to give you a promotion at pysocks issues.

**Comment by woo200** [comment]
Glad it worked out for you.
