### ISSUE TITLE
Using with Ipv6 with Telethon

### ISSUE THREAD

**Issue by Ch4ttY** [licyb200/sockslib#3]
Hi, could you help me to use ur library with telethon with ipv6?
It's opentele library(telethon fork). Thank you!

async with await TelegramClient.FromTDesktop(account=tdesk,
                                                     use_ipv6=True,
                                                     proxy={'proxy_type': sockslib.Socks.SOCKS5,
                                                           'addr': proxy.split(':')[0],
                                                           'port': int(proxy.split(':')[1]),
                                                           'username': proxy.split(':')[2],
                                                           'password': proxy.split(':')[3].replace('\n', ''),
                                                           'rdns': True
                                                           },
                                                     connection_retries=10,
                                                     timeout=2,
                                                     flag=UseCurrentSession
                                                     ) as app:

**Comment by woo200** [comment]
Hi, Telethon is not built to be used with my library, so using their built-in proxy system will probably not work, however you can probably achieve the same result with monkeypatching. Be warned that this will cause all sockets opened to be proxied.

Here is an example usage (Of course substituting whatnot to make your code work)
```python
import sockslib
import socket

authentication = [
    sockslib.NoAuth(),                             # No authentication
    sockslib.UserPassAuth('username', 'password'), # Username / Password authentication
]
sockslib.set_default_proxy(
	('proxy IP', proxy_port),
	sockslib.Socks.SOCKS5,
	socket.AF_INET6,            # This sets it to IPv6
	authentication
)
original_socket = socket.socket      # Save the original socket
socket.socket = sockslib.SocksSocket # Make the default socket object a SocksSocket

async with await TelegramClient.FromTDesktop(
    account=tdesk,
    connection_retries=10,
    timeout=2,
    flag=UseCurrentSession
) as app:
    socket.socket = original_socket # Not neccesary but will probably cause less buggy behavior if you have anything else making connections
    # your code
```

**Comment by Ch4ttY** [comment]
Could you help me to find out, pls?

For some reasons it didn't help to me.
ubuntu==22.04
python==3.10.12
telethon==1.24
sockslib==1.7.6

Attempt 1 at connecting failed: gaierror: [Errno -9] Address family for hostname not supported
![image](https://github.com/woo200/sockslib/assets/11446492/fc053d66-1a69-4f21-b49f-13f1ce33d30a)

**Comment by woo200** [comment]
You told the socket to connect to your proxy with IPv6 but the IP address you entered is a v4 address. Simply remove the ip_protocol argument. Also, for set_default_proxy, you must not include the variable names. e.g replace `socktype=sockslib.Socks.SOCKS5` with just `sockslib.Socks.SOCKS5`. 

It is not necessary to include the ip_protocol parameter in the proxy definition so long as the server is accessible via ipv4, because socks5 proxies will automatically work with ipv6 so long as the socks server itself supports it.

**Comment by Ch4ttY** [comment]
No, it was ipv6 address. Even with ipv6 proxy format it doesn't work, look.
![image](https://github.com/woo200/sockslib/assets/11446492/83ade4d2-2065-4fac-97ed-8807ad8734f9)
![image](https://github.com/woo200/sockslib/assets/11446492/2b174377-0336-4f55-86da-930b7d2d6c26)
![image](https://github.com/woo200/sockslib/assets/11446492/f3efdf44-55ec-45c1-a1ce-18567d8e235a)

**Comment by woo200** [comment]
You are mistaken, That IPv6 address is NOT the proxy address. Use the ip and port that says "Proxy" and use ipv4. If you dont have ipv4 for some reason, you're going to have to find a different proxy service because that proxy is not hosted on ipv6.

**Comment by Ch4ttY** [comment]
I did so in the previous post but with IPv6 settings.

I tried without AF_INET6 and it worked. 
I'm not sure if it used the proxy(Could you help me how to check that the connection uses a proxy?)

So, should I find another provider to use ipv6? And what should the correct ip:port look like in this case?

P.S. This proxy in the format 45.32.117.124:12761 works in telegram portable with the "connect via ipv6" checkbox enabled

**Comment by woo200** [comment]
I don't see what issue you're having. The connection will be using the proxy otherwise it will simply not connect. If the proxy is working what is the issue then? You'll still be able to connect to ipv6 addresses through the proxy

**Comment by Ch4ttY** [comment]
Got it, I will try and share the result later, thank you!

**Comment by Ch4ttY** [comment]
If I need to use 10 accounts with telethon, I can't use set_default_proxy, I need to use set_proxy, right?

**Comment by woo200** [comment]
set_default_proxy applies to all proxy connections you make from then on, if you want to change what proxy you’re using, just run it again before you make the connection.
